Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  # Prometheus Server
  config.vm.network :forwarded_port, guest: 9090, host: 9090
  
  config.vm.provision :ansible do |ansible|
    ansible.host_key_checking = false
    ansible.playbook = "playbook-prometheus.yml"
    ansible.verbose = 'vvv'
    ansible.raw_ssh_args = ['-o ForwardAgent=yes']
  end
end
